# Generated by Django 3.1.4 on 2020-12-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description', max_length=200, null=True),
        ),
    ]
